observation_days = 1
collect_end_days = 6
collect_end_offset = 3000
collect_tags = []
name_keywords = []
tag_keywords = []
exclude_categories = []
video_markers = ["mp4", "video"]
excluded_resolutions = ["1280x", "800x", "1920x", "2560x"]

[urls]
# latest = "https://e-hentai.org/?f_search=..."
